name: Augment Agent - Code Review
on:
  pull_request:
    types: [opened]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create instruction file
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.repository }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          cat > /tmp/review-instruction.txt << EOF
          Perform a comprehensive code review of the following pull request:

          **Pull Request Information:**
          - PR Number: ${PR_NUMBER}
          - Repository: ${REPOSITORY}
          - Base Branch: ${BASE_BRANCH}
          - Head Branch: ${HEAD_BRANCH}

          **Review Focus:**
          Analyze the modified files and provide detailed feedback on:
          - Code quality and adherence to best practices
          - Potential bugs, errors, or security vulnerabilities
          - Performance implications of the changes
          - Suggestions for improvement or optimization
          - Any missing error handling or edge cases
          - Code maintainability and readability

          Please provide specific, actionable feedback with file and line references where applicable.
          Focus on the actual code changes and their impact on the codebase.

          Please post your review as a review comment on the PR. Do not approve or request changes.
          EOF
      - name: Code Review
        uses: augmentcode/augment-agent@v0
        with:
          augment_session_auth: ${{ secrets.AUGMENT_SESSION_AUTH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          instruction_file: /tmp/review-instruction.txt
